.PHONY:all
all:test1 test2 test3 test4 test5 test6 test7

test7:test7.c
	gcc   $^ -o $@ 

test6:test6.c
	gcc   $^ -o $@ -O2

test5:test5.c
	gcc $^ -o $@

test4:test4.c
	gcc $^ -o $@

test3:test3.c
	gcc $^ -o $@

test2:test2.c
	gcc $^ -o $@

test1:test1.c
	gcc $^ -o $@ 
